# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_question_points'),
        ('users', '0002_categorypoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('best_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='categorypoints',
            name='user',
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='categories',
            field=models.ManyToManyField(to='users.CategoryPoints'),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
