# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 04:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160620_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 20, 4, 16, 40, 990279, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
