# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_categorypoints_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypoints',
            name='completed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='completed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
