# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160620_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypoints',
            name='completed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='completed',
            field=models.FloatField(default=0.0),
        ),
    ]
