# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
    ]
