# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=5),
        ),
    ]
